package Enumeradores;

public enum Listar_enum {

	LISTAR_CLIENTES_POR_SEGURO(0), LISTAR_SINISTROS_POR_SEGURADORA(1), LISTAR_SINISTROS_POR_CLIENTE(2),
	LISTAR_VEICULOS_POR_CLIENTE(3), LISTAR_VEICULOS_POR_SEGURADORA(4), LISTAR_FROTAS_POR_CLIENTE(5),
	LISTAR_FROTAS_POR_SEGURADORA(6), LISTAR_SEGUROS_POR_SEGURADORA(7), LISTAR_SEGUROS_POR_CLIENTE(8),
	LISTAR_SEGURADORAS(9), LISTAR_CONDUTORES_POR_SEGURO(10), LISTAR_CONDUTORES_POR_SEGURADORA(11),
	LISTAR_CONDUTORES_POR_CLIENTE(12), VOLTAR(13);

	public final int operacao;

	Listar_enum(int operacao) {
		this.operacao = operacao;
	}

	public int getOperacao() {
		return operacao;
	}
}